project:
  type: website

website:
  title: "Math378Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: model.qmd
        text: Model
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


