project:
  type: website

website:
  title: "Math378Project"
  navbar:
    left:
      - href: index.qmd, eda.qmd, model.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


